/* Autogenerated by Thrift Compiler (0.8.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package main

import (
        "flag"
        "fmt"
        "http"
        "net"
        "os"
        "strconv"
        "thrift"
        "thriftlib/hive_service"
)

func Usage() {
  fmt.Fprint(os.Stderr, "Usage of ", os.Args[0], " [-h host:port] [-u url] [-f[ramed]] function [arg1 [arg2...]]:\n")
  flag.PrintDefaults()
  fmt.Fprint(os.Stderr, "Functions:\n")
  fmt.Fprint(os.Stderr, "  execute(query string) (ex *HiveServerException, err error)\n")
  fmt.Fprint(os.Stderr, "  fetchOne() (retval140 string, ex *HiveServerException, err error)\n")
  fmt.Fprint(os.Stderr, "  fetchN(numRows int32) (retval141 thrift.TList, ex *HiveServerException, err error)\n")
  fmt.Fprint(os.Stderr, "  fetchAll() (retval142 thrift.TList, ex *HiveServerException, err error)\n")
  fmt.Fprint(os.Stderr, "  getSchema() (retval143 *Schema, ex *HiveServerException, err error)\n")
  fmt.Fprint(os.Stderr, "  getThriftSchema() (retval144 *Schema, ex *HiveServerException, err error)\n")
  fmt.Fprint(os.Stderr, "  getClusterStatus() (retval145 *HiveClusterStatus, ex *HiveServerException, err error)\n")
  fmt.Fprint(os.Stderr, "  getQueryPlan() (retval146 *QueryPlan, ex *HiveServerException, err error)\n")
  fmt.Fprint(os.Stderr, "  clean() (err error)\n")
  fmt.Fprint(os.Stderr, "\n")
  os.Exit(0)
}

func main() {
  flag.Usage = Usage
  var host string
  var port int
  var protocol string
  var urlString string
  var framed bool
  var useHttp bool
  var help bool
  var url http.URL
  var trans thrift.TTransport
  flag.Usage = Usage
  flag.StringVar(&host, "h", "localhost", "Specify host and port")
  flag.IntVar(&port, "p", 9090, "Specify port")
  flag.StringVar(&protocol, "P", "binary", "Specify the protocol (binary, compact, simplejson, json)")
  flag.StringVar(&urlString, "u", "", "Specify the url")
  flag.BoolVar(&framed, "framed", false, "Use framed transport")
  flag.BoolVar(&useHttp, "http", false, "Use http")
  flag.BoolVar(&help, "help", false, "See usage string")
  flag.Parse()
  if help || flag.NArg() == 0 {
    flag.Usage()
  }
  
  if len(urlString) > 0 {
    url, err := http.ParseURL(urlString)
    if err != nil {
      fmt.Fprint(os.Stderr, "Error parsing URL: ", err.Error(), "\n")
      flag.Usage()
    }
    host = url.Host
    useHttp = len(url.Scheme) <= 0 || url.Scheme == "http"
  } else if useHttp {
    _, err := http.ParseURL(fmt.Sprint("http://", host, ":", port))
    if err != nil {
      fmt.Fprint(os.Stderr, "Error parsing URL: ", err.Error(), "\n")
      flag.Usage()
    }
  }
  
  cmd := flag.Arg(0)
  var err error
  if useHttp {
    trans, err = thrift.NewTHttpClient(url.Raw)
  } else {
    addr, err := net.ResolveTCPAddr("tcp", fmt.Sprint(host, ":", port))
    if err != nil {
      fmt.Fprint(os.Stderr, "Error resolving address", err.Error())
      os.Exit(1)
    }
    trans, err = thrift.NewTNonblockingSocketAddr(addr)
    if framed {
      trans = thrift.NewTFramedTransport(trans)
    }
  }
  if err != nil {
    fmt.Fprint(os.Stderr, "Error creating transport", err.Error())
    os.Exit(1)
  }
  defer trans.Close()
  var protocolFactory thrift.TProtocolFactory
  switch protocol {
  case "compact":
    protocolFactory = thrift.NewTCompactProtocolFactory()
    break
  case "simplejson":
    protocolFactory = thrift.NewTSimpleJSONProtocolFactory()
    break
  case "json":
    protocolFactory = thrift.NewTJSONProtocolFactory()
    break
  case "binary", "":
    protocolFactory = thrift.NewTBinaryProtocolFactoryDefault()
    break
  default:
    fmt.Fprint(os.Stderr, "Invalid protocol specified: ", protocol, "\n")
    Usage()
    os.Exit(1)
  }
  client := hive_service.NewThriftHiveClientFactory(trans, protocolFactory)
  if err = trans.Open(); err != nil {
    fmt.Fprint(os.Stderr, "Error opening socket to ", host, ":", port, " ", err.Error())
    os.Exit(1)
  }
  
  switch cmd {
  case "execute":
    if flag.NArg() - 1 != 1 {
      fmt.Fprint(os.Stderr, "Execute requires 1 args\n")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.Execute(value0))
    fmt.Print("\n")
    break
  case "fetchOne":
    if flag.NArg() - 1 != 0 {
      fmt.Fprint(os.Stderr, "FetchOne requires 0 args\n")
      flag.Usage()
    }
    fmt.Print(client.FetchOne())
    fmt.Print("\n")
    break
  case "fetchN":
    if flag.NArg() - 1 != 1 {
      fmt.Fprint(os.Stderr, "FetchN requires 1 args\n")
      flag.Usage()
    }
    tmp0, err149 := (strconv.Atoi(flag.Arg(1)))
    if err149 != nil {
      Usage()
      return
    }
    argvalue0 := int32(tmp0)
    value0 := argvalue0
    fmt.Print(client.FetchN(value0))
    fmt.Print("\n")
    break
  case "fetchAll":
    if flag.NArg() - 1 != 0 {
      fmt.Fprint(os.Stderr, "FetchAll requires 0 args\n")
      flag.Usage()
    }
    fmt.Print(client.FetchAll())
    fmt.Print("\n")
    break
  case "getSchema":
    if flag.NArg() - 1 != 0 {
      fmt.Fprint(os.Stderr, "GetSchema requires 0 args\n")
      flag.Usage()
    }
    fmt.Print(client.GetSchema())
    fmt.Print("\n")
    break
  case "getThriftSchema":
    if flag.NArg() - 1 != 0 {
      fmt.Fprint(os.Stderr, "GetThriftSchema requires 0 args\n")
      flag.Usage()
    }
    fmt.Print(client.GetThriftSchema())
    fmt.Print("\n")
    break
  case "getClusterStatus":
    if flag.NArg() - 1 != 0 {
      fmt.Fprint(os.Stderr, "GetClusterStatus requires 0 args\n")
      flag.Usage()
    }
    fmt.Print(client.GetClusterStatus())
    fmt.Print("\n")
    break
  case "getQueryPlan":
    if flag.NArg() - 1 != 0 {
      fmt.Fprint(os.Stderr, "GetQueryPlan requires 0 args\n")
      flag.Usage()
    }
    fmt.Print(client.GetQueryPlan())
    fmt.Print("\n")
    break
  case "clean":
    if flag.NArg() - 1 != 0 {
      fmt.Fprint(os.Stderr, "Clean requires 0 args\n")
      flag.Usage()
    }
    fmt.Print(client.Clean())
    fmt.Print("\n")
    break
  case "":
    Usage()
    break
  default:
    fmt.Fprint(os.Stderr, "Invalid function ", cmd, "\n")
  }
}
